### ISSUE TITLE
FR- Feature Request.- PIN OUTS for RE_ARM Board

### ISSUE THREAD

**Issue by monterman** [etet100/marlin_cetus_3d#1]
FR- Feature Request.- PIN OUTS for RE_ARM Board

Could you share the pin-outs form Cetus 3D Board to the ARDUINO Compatible board, IE Re ARM. 

This way any Arduino Compatible Board could be hooked up to the Cetus with your MARLIN 2.0 code.

Since we want to use a 32 bit board, a Re-ARM board would be the best alternative to test out the Cetus once all pins are connected.  

thanks, monterman

**Comment by etet100** [comment]
Hi. Re-ARM is NXP board. My goal is to use cheap STM32 board (F103 or F303).
